### ISSUE TITLE
Scrollbar missing for Input Directories in Graphical Editor

### ISSUE THREAD

**Issue by reneparis** [anb0s/eclox#167]
Hey Andre,

When I added a new directory using the "input directory" list within the graphical editor, I first believed that nothing happened. At second glance I realized, that the directory was added, but at the end of the list, which was not visible anymore (as there are already a lot of other directories). I used a mouse drag within the listview to scroll down, which worked. Consequently it would be nice to have a scrollbar ;)

Great work!

**Comment by anb0s** [comment]
Thanks René! I will add this for next release.

**Comment by anb0s** [comment]
done for 0.11.0
