### ISSUE TITLE
Feature Request: Change @ to \ for doxygen comments

### ISSUE THREAD

**Issue by reneparis** [anb0s/eclox#168]
Hey,

I'm forced to worke with "old style" comments, such as \param and \return.
It would be nice if there is a possibility to change the opening character.

Thanks!

**Comment by anb0s** [comment]
Eclox has support for the features (only):
- Graphical edition of doxyfile settings
- integrated doxygen invocation
- doxygen outputs logging and
- optional packaged doxygen binaries (for windows and linux)

Eclox has no support for writing comments (content assists etc.) in source files. The only setting i know comes from CDT and it supports all C/C++ file types (h, c, cpp): one has to enable it  for the workspace or the project (like @Corderbollie described in #185). Then you have some simple generation of the comment block -> just remove the comments from your function / method etc. and then type '/**' + ENTER. Then it generates something like this:
```
/**
 *
 * @param ...
 * @return
 */
```

**Comment by anb0s** [comment]
see #2

**Comment by anb0s** [comment]
see issue in CDT:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=333134
