### ISSUE TITLE
Sorting column in Advanced tab

### ISSUE THREAD

**Issue by HolgerNie** [anb0s/eclox#171]
It would be great if the columns under the Advanced tab could be sorted in alphabetical order. That would make it easier to find an entry. However doxygen is working fine for me under Eclipse. Great job.

**Comment by anb0s** [comment]
Thanks! I will add it for the next relase.

**Comment by anb0s** [comment]
done

**NONE**
![image](https://cloud.githubusercontent.com/assets/95811/23206351/9718e73a-f8ed-11e6-9c4f-c150028e6862.png)

**ascending**
![image](https://cloud.githubusercontent.com/assets/95811/23206368/a6b00f66-f8ed-11e6-83ee-474257cbf48e.png)

**descending**
![image](https://cloud.githubusercontent.com/assets/95811/23206376/b3b0a9a0-f8ed-11e6-9a85-51ab22cbfc7c.png)
