### ISSUE TITLE
Support resources in linked folders

### ISSUE THREAD

**Issue by Corderbollie** [anb0s/eclox#176]
Hi.
I noticed that eclox is not able to create markers from doxygen messages that are related to files located in linked folders.
Some time ago I changed version 0.10.1 of eclox for my own to also create markers from messages related to such sources. I have attached the diff file here.
It would be nice if you could integrate that change also into your code.
[eclox_linkedresources.txt](https://github.com/anb0s/eclox/files/718601/eclox_linkedresources.txt)

**Comment by anb0s** [comment]
Thank You! I will fix this for next release.

**Comment by anb0s** [comment]
fixed for 0.11.0 beta 1

**Comment by anb0s** [comment]
fixed with #177
