### ISSUE TITLE
No groups on advanced tab

### ISSUE THREAD

**Issue by Corderbollie** [anb0s/eclox#178]
Hi.
Just installed 0.11.0.v20170121-2217 for testing and noticed that the options on the advanced tab of the doxy filey editor are not assigned to a group anymore.

The only group available is 'Others'. When I clikc any option I get an error in the error log view like:

org.gna.eclox.ui
Error encountered. DOXYFILE_ENCODING: missing or wrong TYPE property.
Error encountered. DOXYFILE_ENCODING: missing TEXT property.

The options are all in the list however there is no group assigned to them.

**Comment by anb0s** [comment]
Thanks! I will investigate...

**Comment by anb0s** [comment]
No groups:
![image](https://cloud.githubusercontent.com/assets/95811/22242064/421a2bfe-e222-11e6-86d0-ee9451c757e4.png)

**Comment by anb0s** [comment]
Exception after selection:
![image](https://cloud.githubusercontent.com/assets/95811/22242100/63c5f4ea-e222-11e6-8433-cdf3da2285bf.png)

...
null
org.gna.eclox.ui
Error
Tue Jan 24 10:45:11 CET 2017
Error encountered. DOXYFILE_ENCODING: missing TEXT property.
...
null
org.gna.eclox.ui
Error
Tue Jan 24 10:45:11 CET 2017
Error encountered. DOXYFILE_ENCODING: missing or wrong TYPE property.
...

**Comment by anb0s** [comment]
fixed
