### ISSUE TITLE
Problem with version 0.11 and IDE 3.8.2

### ISSUE THREAD

**Issue by HolgerNie** [anb0s/eclox#179]
I tried to install the new version 0.11 but without success. We are using a IDE which is based on eclipse 3.8.2. With version 0.10 everything is fine. I do not see the icon in the toolbar nor are *.doxyfiles are opend

**Comment by anb0s** [comment]
Do you see any exceptions etc. relatred to eclox in "Error Log" View?

**Comment by HolgerNie** [comment]
So far i do not see any error. The installation itself runs complety without any fault message.
[WRS.zip](https://github.com/anb0s/eclox/files/731889/WRS.zip)

**Comment by anb0s** [comment]
Thanks. I see only the error from update service:
org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at http://marketplace.eclipse.org/content/eclox.

This is a marketplace link, the update site is: http://anb0s.github.io/eclox/testing

Anyway please check if eclox was really updated installed and what version is it ?

**Comment by HolgerNie** [comment]
I have done the installation always from the update site. The marketplace link was old and I removed it from the update side list.
I have attached screen shot after the installation so far it looks good but I do not see any icon nor can open the *.doxyfiles with the correct editor.
![eclox3](https://cloud.githubusercontent.com/assets/12135505/22363209/ee6f27c2-e468-11e6-8738-3d24280766a9.PNG)
![eclox2](https://cloud.githubusercontent.com/assets/12135505/22363242/34ad7536-e469-11e6-95ab-e7220d4634e2.PNG)

![eclox1](https://cloud.githubusercontent.com/assets/12135505/22362728/1b623700-e465-11e6-8828-25f3b53d8646.PNG)

**Comment by anb0s** [comment]
I've just tried Eclipse 3.8.2 with 0.11.x build and it worked. Showing the .doxygen files and also building was OK:. 
![image](https://cloud.githubusercontent.com/assets/95811/22863697/8d3a8e1c-f145-11e6-984a-15423ec3b7ec.png)

So, i've no idea what is different in your installation...

**Comment by HolgerNie** [comment]
Thanks, it seems that I have the same version. I installed several times the 10 and the 11 version. 10 is always working 11 isn’t. I will stay on the 10 version, thanks.
![unbenannt](https://cloud.githubusercontent.com/assets/12135505/22874360/e13b19ca-f1c5-11e6-9244-60e1ef9a1497.PNG)

**Comment by anb0s** [comment]
Please try to start eclipse with "-debug" option and look if the output shows something about class loader errors or eclox etc.

**Comment by anb0s** [comment]
May be manual installation does help:

**Manual instal**: see http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fp2_dropins_format.html

create the folder structure under your eclipse directory (here eclipse):
```
eclipse/
    dropins/
      eclox/
       eclipse/
         features/
         plugins/ 

```
and copy the jar files files from here: https://github.com/anb0s/eclox/tree/master/eclox.site/updates/testing/0.11/0.11.0.v20170121-2217
to local features and plugins subfolders under eclox/eclipse.

**Comment by HolgerNie** [comment]
I tried the dropins folder both but without success. The debug printout is attached. Still version 10 is working fine 11 not.
[new 1.txt](https://github.com/anb0s/eclox/files/771276/new.1.txt)

**Comment by anb0s** [comment]
Thanks! Now i see that JRE 6 (jre/1.6.0_21) is used in your installation. Eclox 0.11 is working with Java 7 (1.7) only and i think the eclox classes compiled with Java 7 are not loaded :(

I've checked that the minimum requirement Java 1.7 is set in all eclox plugin files and marketplace entry:
![image](https://cloud.githubusercontent.com/assets/95811/22891152/ba923e54-f20e-11e6-9095-1f49f601d535.png)

, so i do not know why the Eclipse installation allow you to install this version...

I've Eclipse 3.8.2 (win32) here with Java 7 and Java 8 working. Is it possible to use Java 7 for you?

**Comment by HolgerNie** [comment]
I changed to jre 1.8.0_45 and version 11 is working. Thanks

**Comment by anb0s** [comment]
Thanks!
