### ISSUE TITLE
Add support for C/C++ header files

### ISSUE THREAD

**Issue by aarian93p** [anb0s/eclox#185]
The Eclox doesn't recognizes the doxygen comments in the header files (.h) while the doxygen supports and parses them. I think it would be nice if you add a say checkbox in the doxygen page in the preferences which allows us to enable the eclox for headers or something like that.

**Comment by Corderbollie** [comment]
Maybe you forgot to select doxygen to be the default documentation tool for C/C++ Editors?
Have a look into 'Window > Preferences > C/C++ > Editor > Documentation tool comments' an set the Workspace default to 'Doxygen'

**Comment by anb0s** [comment]
@aarian93p does the hint from @Corderbollie helps you?

**Comment by aarian93p** [comment]
Hi

Unfortunately not!


On Apr 13, 2017 3:08 PM, "Andre Bossert" <notifications@github.com> wrote:

@aarian93p <https://github.com/aarian93p> does the hint from @Corderbollie
<https://github.com/Corderbollie> helps you?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/anb0s/eclox/issues/185#issuecomment-293854487>, or mute
the thread

**Comment by anb0s** [comment]
> The Eclox doesn't recognizes the doxygen comments in the header files (.h)

I do not understand how eclox should help with header files or cpp files? Eclox has support for the features (only):
- Graphical edition of doxyfile settings
- integrated doxygen invocation
- doxygen outputs logging and
- optional packaged doxygen binaries (for windows and linux)

Eclox has no support for writing comments (content assists etc.) in source files. The only setting i know comes from CDT and it supports all C/C++ file types (h, c, cpp): one has to enable it  for the workspace or the project (like @Corderbollie described). Then you have some simple generation of the comment block -> just remove the comments from your function / method etc. and then type '/**' + ENTER. Then it generates something like this:
```
/**
 *
 * @param ...
 * @return
 */
```
I works for header files too in my Eclipse Neon + CDT 9.2...

**Comment by anb0s** [comment]
see #2
