### ISSUE TITLE
Doxygen build doesn't seem to get a valid file system path to doxyfile

### ISSUE THREAD

**Issue by madsci77** [anb0s/eclox#190]
I'm running Freescale CodeWarrior 10.7, which is based on Eclipse Juno.  Yesterday I had eclox 0.8.0 working with one project, but others gave the "endRule without matching beginRule" error, which I saw had been fixed.  I installed 0.11.0 but it didn't work at all - no option to create a doxyfile, and no @ icon.  I installed 0.10.0 instead and got the doxyfile editor back, and it _tries_ to launch doxygen but completes immediately with "*** Build finished!".

I think the problem is that it's launching doxygen with a project-relative path and not a file system path.  The build job history shows something like this:

/MyProjectName/Documentation/doxygen/MyProjectName.doxyfile

The console says it's executing doxygen -b with the above path.  If that's right, it's omitting the drive letter and the rest of the path.  If I run doxygen -b from the command line and give it the full path to the doxyfile it runs just fine - and for now I can get by with a batch file to do that.

I can't find any way to change how the path is passed to doxygen.  I choose the doxyfile using the @ icon, but it gives me a project-relative file picker.  I have no option to select a file by file system path.  I also can't figure out where stdout goes so I can test my theory.  Is there perhaps an environment variable that Eclipse needs to be setting?

Thanks!

**Comment by anb0s** [comment]
Thanks for the report. I've improved the 0.11.x versions only and cannot say much about the 0.10.x. For the 0.11.0 i'm testing Eclipse 3.8 and 4.3-4.7. The Eclipse 4.2.x is buggy.... it looks like Freescale CodeWarrior 10.7 based at 4.2.x stream :( so i cannot promise it works with it and do not know yet if i find time to test it too...

**Comment by anb0s** [comment]
I've just tested the eclox 0.11.1 with Eclipse 4.2.x (Juno) and it it works! Please try this version again and give  more information about the error or may be log file?

**Comment by anb0s** [comment]
![image](https://cloud.githubusercontent.com/assets/95811/25457054/315f79bc-2ad5-11e7-9a46-3150c1490d72.png)

**Comment by madsci77** [comment]
Ok, reinstalled 0.11.1 and I get no @ icon, and this is in the log:
```

!ENTRY org.eclipse.osgi 2 1 2017-04-26 14:10:13.310
!MESSAGE NLS missing message: ContentTypes_errorDialogAlreadyExists in: org.ecli
pse.ui.internal.messages

!ENTRY org.eclipse.ui 4 4 2017-04-26 14:10:14.467
!MESSAGE Unable to find Action Set: eclox.ui.buildActionSet

```

**Comment by anb0s** [comment]
ok strange, do you see any other eclox menues like the context menu if selecting doxyfile?
![image](https://cloud.githubusercontent.com/assets/95811/25458010/87f05dde-2ad8-11e7-8c92-2e2bf3a32988.png)

or prefernces:
![image](https://cloud.githubusercontent.com/assets/95811/25458049/a6dbacb2-2ad8-11e7-9a6f-3b72359dc88f.png)

**Comment by madsci77** [comment]
Nope.
![screenshot 2017-04-26 14 33 33](https://cloud.githubusercontent.com/assets/22358906/25458120/7ae4d728-2a8d-11e7-9034-82a587a3c242.png)

**Comment by madsci77** [comment]
And just to be sure it IS installed, here's the installed software list.

![screenshot 2017-04-26 14 39 15](https://cloud.githubusercontent.com/assets/22358906/25458293/31763af4-2a8e-11e7-97b2-0361117dadc2.png)

**Comment by HolgerNie** [comment]
Maybe the same problem that I had #179?

**Comment by anb0s** [comment]
@HolgerNie Thanks!
@madsci77 please verify if you have Java 6 (1.6) in use. eclox 0.11 is working with Java 7 or 8 only

**Comment by madsci77** [comment]
Ok, that's definitely on the right track.  I'm running 1.8.0_131, but it turns out CodeWarrior comes with its own JVM.  (Reminds me of my days as an Oracle DBA, with half a dozen different incompatible JVMs installed at any given time.)  I ran cwide (aka eclipse) with -vm and the current Java path and now Eclox shows up.  When I run doxygen, though, it crashes with a NullPointerException, seemingly after it's finished.  I see 'finished...' in the log and no errors there.  In the Eclipse log I get:

```
!ENTRY org.gna.eclox.core 4 0 2017-05-04 09:16:37.405
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at eclox.core.doxyfiles.Doxyfile.getOutputContainer(Doxyfile.java:232)
	at eclox.core.doxygen.BuildJob.run(BuildJob.java:470)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

```

I may have to just skip it, or stick with version 10.  If NXP isn't keeping up with Java releases, who knows what else in that installation might break.  I have enough time getting any support out of them when I'm running the default configuration and paying an annual maintenance fee.

**Comment by anb0s** [comment]
@madsci77 Thanks for verification and sorry for the found bug. I can reproduce it and i've created new issue for this #191 I'm just curious the code is same in 0.8.x and 0.10.x in this file and why it shows up now in 0.11.x stream only...

**Comment by anb0s** [comment]
Please check the testing version from #194 
Please close this issue if you can work with 0.11.x and Java 7/8
Thanks!

**Comment by madsci77** [comment]
Thanks, will do.

**Comment by AlaaElnagar** [comment]
SOLVED !!! HERE http://sirius5206.top/doku.php?id=tips:eclipse:eclox
