### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by olivierlopez44** [anb0s/eclox#210]
I've got this problem that occure when i execute eclox.
i got the last version of eclox.

**Comment by anb0s** [comment]
Please provide some information:
- eclox version: latest 0.11.2?
- opertaing system:
- eclipse version:
- please copy and paste the whole exception (callstack) here

May be it's related to #195 

Thanks!

**Comment by olivierlopez44** [comment]
eclox version : 0.11.2.v20170504-1955
on windows 10 Pro
Eclipse mars.2 release 4.5.2

https://image.noelshack.com/fichiers/2017/37/2/1505226958-error.png

**Comment by anb0s** [comment]
Thanks!
It looks like related to #195 and is fixed in 0.12.0 testing version
Please checkout the latest testing version if possible: #209 
OR wait for the 0.12.x release.

**Comment by anb0s** [comment]
@olivierlopez44 does the testing version 0.12.0 works for you?

**Comment by olivierlopez44** [comment]
yeah the version 0.12.0 works for me, sorry for not telling you.
Thanks

**Comment by anb0s** [comment]
Thanks!
