### ISSUE TITLE
java.lang.NoSuchFieldError:INSTANCE while trying build using eclipse helios

### ISSUE THREAD

**Issue by pawandazzler** [anb0s/eclox#217]
I tried installing Eclox from software site as well as from downloaded zip content. While i am trying to build using DoxyFile for C++ project it throws error java.lang.NoSuchFieldError:INSTANCE unexpected error. My eclipse is
Eclipse IDE for C/C++ Developers
Version: Helios Service Release 2
Build id: 20110218-0911
And i am working on Windows 10 64 bit version

**Comment by anb0s** [comment]
I'm testing eclox with Eclipse 3.8 - 4.7. Helios is 3.6. I've no free time to verify such "old" versions... if somebody needs it, please help...

**Comment by anb0s** [comment]
Close this --> the minimum version of supported Eclipse is 3.8
