### ISSUE TITLE
Is there a way to get version 0.8.0 for Eclipse 3.6.x which was available via http://download.gna.org/eclox/update

### ISSUE THREAD

**Issue by efelon** [anb0s/eclox#224]
Hi,

i'm unfortunately dependent on an old eclipse version (3.6.2) for which I was only able to get eclox doxygen connector 0.8.0 to work. This was available on the update site http://download.gna.org/eclox/update. Is there a way to get this old version installed via an update site?

I tried https://anb0s.github.io/eclox/ which is not recognized.

Thank you in advance,
Martin

**Comment by anb0s** [comment]
Hi,

i've moved all old update site files as composite site to GitHub and it shows up in Eclipse 4.x:
![image](https://user-images.githubusercontent.com/95811/37518426-61a1b4a2-2915-11e8-8caf-9bf0d0730414.png)

I think the p2 composite site is not working with Eclipse 3.6. You can see the site structure at: https://github.com/anb0s/eclox/tree/gh-pages/release and it's the root for https://anb0s.github.io/eclox/ i've tried to add sub-dir. e.g.: https://anb0s.github.io/eclox/0.08-0.10
but it's not working...

 I've uploaded the update site 0.08-0.10 to last 0.10.x release:
https://github.com/anb0s/eclox/releases/download/eclox-0.10.2-fixed/Eclox-0.08-0.10.zip

You can download this archive, extract and install it as local site in Eclipse.

**Comment by efelon** [comment]
First, thanks a lot for the quick help. I got it working but had to modify the zip.

There is a top level directory "0.08-0.10" within your zip file. If you only zip the content of this directory it's working out of the box.

[0.08-0.10.zip](https://github.com/anb0s/eclox/files/1819087/0.08-0.10.zip)

**Comment by anb0s** [comment]
Ah, i see, thanks! I've uploaded the new archive to same location.
