### ISSUE TITLE
Eclox not working with Eclispe 2018-09

### ISSUE THREAD

**Issue by HolgerNie** [anb0s/eclox#226]
## Expected Behavior
Eclox should work with Eclispe 2018-09

## Actual Behavior
Eclox not working with Eclispe 2018-09

## Steps to Reproduce the Problem
Installed form the marketplace but no icon or editor can be found after installation.

## Your Environment

- Eclox Plugin version: 0.12.1
- Eclox Doxygen Plugin version: **{version}**
- Eclipse Version: 2018-09 (4.9.0)
- Java Version: 1.8
- Operating System Version: Win 7

**Comment by anb0s** [comment]
I'm using eclox with Eclipse 2018-09 and do not see any problem. Here the screenshot from Eclipse IDE for C/C++ and the Eclox icon is there:

![image](https://user-images.githubusercontent.com/95811/50887342-3cd3b980-13f3-11e9-808a-16024c41dc31.png)

Do you have eclox related errors in the error view or may be log file etc. ?

**Comment by HolgerNie** [comment]
I've tried several things. Installation from Marketplace, no error message but no icons etc. 

After I started Eclipse with **administrator rights** and made the installation from the Marketplace I see the icon and can work with the program.

I can't say why this is so.

**Comment by anb0s** [comment]
Hm, that is strange. It looks like the update cannot access folders / extract plugin files if not running as admin. I've no idea how to tweak this from plugin itself...

**Comment by anb0s** [comment]
Please re-open if reproduceable and more information vailable, thanks
