### ISSUE TITLE
Create eclipse problem markers for doxygen errors and warnings

### ISSUE THREAD

**Issue by lordyavin** [anb0s/eclox#234]
## Expected Behavior
**Each doxygen error and warning shall be added as eclipse problems markers to mark corresponding sources.**

## Actual Behavior
**Source code is not marked with doxygen errors or warnings.**

## Steps to Reproduce the Problem
**Run doxygen on sources that generates warnings and errors.**

## Your Environment

- Eclox Plugin version: **0.12.1**
- Eclox Doxygen Plugin version: **1.8.13**
- Eclipse Version: **4.12 R2019-06**
- Java Version: **11**
- Operating System Version: **Windows 7**

**Comment by lordyavin** [comment]
Mh, know it works. Don't know what I changed but probelm markers are created now.

**Comment by lordyavin** [comment]
The problems markers are shown in the editor but not in the Problems view.

**Comment by anb0s** [comment]
investigating, please try testing build #236

**Comment by lordyavin** [comment]
Just remembered that this issue is pending. With 

* Eclox 0.12.1.v20180118-1753
* Doxygen binaries 1.8.16.v20191028-2041	
* Eclipse Platform 2019-12 (4.14, I20191210-0610)

it currently works.
