### ISSUE TITLE
Strange behaviour regarding call and caller graph with graphviz dot

### ISSUE THREAD

**Issue by Covarians** [anb0s/eclox#240]
## Expected Behavior
When HAVE_DOT, CALL_GRAPH and CALLER_GRAPH are on YES I should have call and caller graph visible on all functions.

## Actual Behavior
Sometime graphs appear for some functions and sometime they do not appear for the same functions. I have not been able to identify a change that would induce this effect. Soemtime in the same build I have graphs for one function and not for some others although I know they are calling functions.

## Steps to Reproduce the Problem
Very difficult. I have not been able to restore the graph in some cases.

## Your Environment

- Eclox Plugin version: 0.12.1
- Eclox Doxygen Plugin version: **{version}**
- Eclipse Version: Code Composer Studio 10.1 (Eclipse platform 4.14
- Java Version: 8 (upgrade 231)
- Operating System Version: Windows10 (latest)

**Comment by anb0s** [comment]
Thanks for the report. I think this is not related to eclox plugin itself as it "only" gives you an editor for doxyfiles and it "just" calls doxygen executable for generating or updating the files. Eclox itself does not render or change the doxyfiles. May be you can provide your configuration to [doxygen project](https://github.com/doxygen/doxygen/issues) and ask there?
